package com.hg.hgc.web.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.Iterator;

public class CustomExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public CustomExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andCustomidIsNull() {
			addCriterion("customID is null");
			return (Criteria) this;
		}

		public Criteria andCustomidIsNotNull() {
			addCriterion("customID is not null");
			return (Criteria) this;
		}

		public Criteria andCustomidEqualTo(Integer value) {
			addCriterion("customID =", value, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidNotEqualTo(Integer value) {
			addCriterion("customID <>", value, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidGreaterThan(Integer value) {
			addCriterion("customID >", value, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidGreaterThanOrEqualTo(Integer value) {
			addCriterion("customID >=", value, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidLessThan(Integer value) {
			addCriterion("customID <", value, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidLessThanOrEqualTo(Integer value) {
			addCriterion("customID <=", value, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidIn(List<Integer> values) {
			addCriterion("customID in", values, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidNotIn(List<Integer> values) {
			addCriterion("customID not in", values, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidBetween(Integer value1, Integer value2) {
			addCriterion("customID between", value1, value2, "customid");
			return (Criteria) this;
		}

		public Criteria andCustomidNotBetween(Integer value1, Integer value2) {
			addCriterion("customID not between", value1, value2, "customid");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPwdIsNull() {
			addCriterion("pwd is null");
			return (Criteria) this;
		}

		public Criteria andPwdIsNotNull() {
			addCriterion("pwd is not null");
			return (Criteria) this;
		}

		public Criteria andPwdEqualTo(String value) {
			addCriterion("pwd =", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotEqualTo(String value) {
			addCriterion("pwd <>", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdGreaterThan(String value) {
			addCriterion("pwd >", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdGreaterThanOrEqualTo(String value) {
			addCriterion("pwd >=", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLessThan(String value) {
			addCriterion("pwd <", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLessThanOrEqualTo(String value) {
			addCriterion("pwd <=", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLike(String value) {
			addCriterion("pwd like", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotLike(String value) {
			addCriterion("pwd not like", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdIn(List<String> values) {
			addCriterion("pwd in", values, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotIn(List<String> values) {
			addCriterion("pwd not in", values, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdBetween(String value1, String value2) {
			addCriterion("pwd between", value1, value2, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotBetween(String value1, String value2) {
			addCriterion("pwd not between", value1, value2, "pwd");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andMobile2IsNull() {
			addCriterion("mobile2 is null");
			return (Criteria) this;
		}

		public Criteria andMobile2IsNotNull() {
			addCriterion("mobile2 is not null");
			return (Criteria) this;
		}

		public Criteria andMobile2EqualTo(String value) {
			addCriterion("mobile2 =", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2NotEqualTo(String value) {
			addCriterion("mobile2 <>", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2GreaterThan(String value) {
			addCriterion("mobile2 >", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2GreaterThanOrEqualTo(String value) {
			addCriterion("mobile2 >=", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2LessThan(String value) {
			addCriterion("mobile2 <", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2LessThanOrEqualTo(String value) {
			addCriterion("mobile2 <=", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2Like(String value) {
			addCriterion("mobile2 like", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2NotLike(String value) {
			addCriterion("mobile2 not like", value, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2In(List<String> values) {
			addCriterion("mobile2 in", values, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2NotIn(List<String> values) {
			addCriterion("mobile2 not in", values, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2Between(String value1, String value2) {
			addCriterion("mobile2 between", value1, value2, "mobile2");
			return (Criteria) this;
		}

		public Criteria andMobile2NotBetween(String value1, String value2) {
			addCriterion("mobile2 not between", value1, value2, "mobile2");
			return (Criteria) this;
		}

		public Criteria andIntroduceIsNull() {
			addCriterion("introduce is null");
			return (Criteria) this;
		}

		public Criteria andIntroduceIsNotNull() {
			addCriterion("introduce is not null");
			return (Criteria) this;
		}

		public Criteria andIntroduceEqualTo(String value) {
			addCriterion("introduce =", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotEqualTo(String value) {
			addCriterion("introduce <>", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceGreaterThan(String value) {
			addCriterion("introduce >", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceGreaterThanOrEqualTo(String value) {
			addCriterion("introduce >=", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLessThan(String value) {
			addCriterion("introduce <", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLessThanOrEqualTo(String value) {
			addCriterion("introduce <=", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceLike(String value) {
			addCriterion("introduce like", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotLike(String value) {
			addCriterion("introduce not like", value, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceIn(List<String> values) {
			addCriterion("introduce in", values, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotIn(List<String> values) {
			addCriterion("introduce not in", values, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceBetween(String value1, String value2) {
			addCriterion("introduce between", value1, value2, "introduce");
			return (Criteria) this;
		}

		public Criteria andIntroduceNotBetween(String value1, String value2) {
			addCriterion("introduce not between", value1, value2, "introduce");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Byte value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Byte value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Byte value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Byte value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Byte value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Byte> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Byte> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Byte value1, Byte value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Byte value1, Byte value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andOccupationIsNull() {
			addCriterion("occupation is null");
			return (Criteria) this;
		}

		public Criteria andOccupationIsNotNull() {
			addCriterion("occupation is not null");
			return (Criteria) this;
		}

		public Criteria andOccupationEqualTo(String value) {
			addCriterion("occupation =", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotEqualTo(String value) {
			addCriterion("occupation <>", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationGreaterThan(String value) {
			addCriterion("occupation >", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationGreaterThanOrEqualTo(String value) {
			addCriterion("occupation >=", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationLessThan(String value) {
			addCriterion("occupation <", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationLessThanOrEqualTo(String value) {
			addCriterion("occupation <=", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationLike(String value) {
			addCriterion("occupation like", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotLike(String value) {
			addCriterion("occupation not like", value, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationIn(List<String> values) {
			addCriterion("occupation in", values, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotIn(List<String> values) {
			addCriterion("occupation not in", values, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationBetween(String value1, String value2) {
			addCriterion("occupation between", value1, value2, "occupation");
			return (Criteria) this;
		}

		public Criteria andOccupationNotBetween(String value1, String value2) {
			addCriterion("occupation not between", value1, value2, "occupation");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathIsNull() {
			addCriterion("IDCardFilePath is null");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathIsNotNull() {
			addCriterion("IDCardFilePath is not null");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathEqualTo(String value) {
			addCriterion("IDCardFilePath =", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathNotEqualTo(String value) {
			addCriterion("IDCardFilePath <>", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathGreaterThan(String value) {
			addCriterion("IDCardFilePath >", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathGreaterThanOrEqualTo(String value) {
			addCriterion("IDCardFilePath >=", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathLessThan(String value) {
			addCriterion("IDCardFilePath <", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathLessThanOrEqualTo(String value) {
			addCriterion("IDCardFilePath <=", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathLike(String value) {
			addCriterion("IDCardFilePath like", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathNotLike(String value) {
			addCriterion("IDCardFilePath not like", value, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathIn(List<String> values) {
			addCriterion("IDCardFilePath in", values, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathNotIn(List<String> values) {
			addCriterion("IDCardFilePath not in", values, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathBetween(String value1, String value2) {
			addCriterion("IDCardFilePath between", value1, value2, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardfilepathNotBetween(String value1, String value2) {
			addCriterion("IDCardFilePath not between", value1, value2, "idcardfilepath");
			return (Criteria) this;
		}

		public Criteria andIdcardauthIsNull() {
			addCriterion("IDCardAuth is null");
			return (Criteria) this;
		}

		public Criteria andIdcardauthIsNotNull() {
			addCriterion("IDCardAuth is not null");
			return (Criteria) this;
		}

		public Criteria andIdcardauthEqualTo(String value) {
			addCriterion("IDCardAuth =", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthNotEqualTo(String value) {
			addCriterion("IDCardAuth <>", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthGreaterThan(String value) {
			addCriterion("IDCardAuth >", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthGreaterThanOrEqualTo(String value) {
			addCriterion("IDCardAuth >=", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthLessThan(String value) {
			addCriterion("IDCardAuth <", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthLessThanOrEqualTo(String value) {
			addCriterion("IDCardAuth <=", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthLike(String value) {
			addCriterion("IDCardAuth like", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthNotLike(String value) {
			addCriterion("IDCardAuth not like", value, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthIn(List<String> values) {
			addCriterion("IDCardAuth in", values, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthNotIn(List<String> values) {
			addCriterion("IDCardAuth not in", values, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthBetween(String value1, String value2) {
			addCriterion("IDCardAuth between", value1, value2, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andIdcardauthNotBetween(String value1, String value2) {
			addCriterion("IDCardAuth not between", value1, value2, "idcardauth");
			return (Criteria) this;
		}

		public Criteria andLogofilepathIsNull() {
			addCriterion("logoFilePath is null");
			return (Criteria) this;
		}

		public Criteria andLogofilepathIsNotNull() {
			addCriterion("logoFilePath is not null");
			return (Criteria) this;
		}

		public Criteria andLogofilepathEqualTo(String value) {
			addCriterion("logoFilePath =", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathNotEqualTo(String value) {
			addCriterion("logoFilePath <>", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathGreaterThan(String value) {
			addCriterion("logoFilePath >", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathGreaterThanOrEqualTo(String value) {
			addCriterion("logoFilePath >=", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathLessThan(String value) {
			addCriterion("logoFilePath <", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathLessThanOrEqualTo(String value) {
			addCriterion("logoFilePath <=", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathLike(String value) {
			addCriterion("logoFilePath like", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathNotLike(String value) {
			addCriterion("logoFilePath not like", value, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathIn(List<String> values) {
			addCriterion("logoFilePath in", values, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathNotIn(List<String> values) {
			addCriterion("logoFilePath not in", values, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathBetween(String value1, String value2) {
			addCriterion("logoFilePath between", value1, value2, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andLogofilepathNotBetween(String value1, String value2) {
			addCriterion("logoFilePath not between", value1, value2, "logofilepath");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andHometownIsNull() {
			addCriterion("hometown is null");
			return (Criteria) this;
		}

		public Criteria andHometownIsNotNull() {
			addCriterion("hometown is not null");
			return (Criteria) this;
		}

		public Criteria andHometownEqualTo(String value) {
			addCriterion("hometown =", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownNotEqualTo(String value) {
			addCriterion("hometown <>", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownGreaterThan(String value) {
			addCriterion("hometown >", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownGreaterThanOrEqualTo(String value) {
			addCriterion("hometown >=", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownLessThan(String value) {
			addCriterion("hometown <", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownLessThanOrEqualTo(String value) {
			addCriterion("hometown <=", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownLike(String value) {
			addCriterion("hometown like", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownNotLike(String value) {
			addCriterion("hometown not like", value, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownIn(List<String> values) {
			addCriterion("hometown in", values, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownNotIn(List<String> values) {
			addCriterion("hometown not in", values, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownBetween(String value1, String value2) {
			addCriterion("hometown between", value1, value2, "hometown");
			return (Criteria) this;
		}

		public Criteria andHometownNotBetween(String value1, String value2) {
			addCriterion("hometown not between", value1, value2, "hometown");
			return (Criteria) this;
		}

		public Criteria andHighesteducationIsNull() {
			addCriterion("highestEducation is null");
			return (Criteria) this;
		}

		public Criteria andHighesteducationIsNotNull() {
			addCriterion("highestEducation is not null");
			return (Criteria) this;
		}

		public Criteria andHighesteducationEqualTo(String value) {
			addCriterion("highestEducation =", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationNotEqualTo(String value) {
			addCriterion("highestEducation <>", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationGreaterThan(String value) {
			addCriterion("highestEducation >", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationGreaterThanOrEqualTo(String value) {
			addCriterion("highestEducation >=", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationLessThan(String value) {
			addCriterion("highestEducation <", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationLessThanOrEqualTo(String value) {
			addCriterion("highestEducation <=", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationLike(String value) {
			addCriterion("highestEducation like", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationNotLike(String value) {
			addCriterion("highestEducation not like", value, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationIn(List<String> values) {
			addCriterion("highestEducation in", values, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationNotIn(List<String> values) {
			addCriterion("highestEducation not in", values, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationBetween(String value1, String value2) {
			addCriterion("highestEducation between", value1, value2, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andHighesteducationNotBetween(String value1, String value2) {
			addCriterion("highestEducation not between", value1, value2, "highesteducation");
			return (Criteria) this;
		}

		public Criteria andCollegeIsNull() {
			addCriterion("college is null");
			return (Criteria) this;
		}

		public Criteria andCollegeIsNotNull() {
			addCriterion("college is not null");
			return (Criteria) this;
		}

		public Criteria andCollegeEqualTo(String value) {
			addCriterion("college =", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotEqualTo(String value) {
			addCriterion("college <>", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeGreaterThan(String value) {
			addCriterion("college >", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeGreaterThanOrEqualTo(String value) {
			addCriterion("college >=", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeLessThan(String value) {
			addCriterion("college <", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeLessThanOrEqualTo(String value) {
			addCriterion("college <=", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeLike(String value) {
			addCriterion("college like", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotLike(String value) {
			addCriterion("college not like", value, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeIn(List<String> values) {
			addCriterion("college in", values, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotIn(List<String> values) {
			addCriterion("college not in", values, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeBetween(String value1, String value2) {
			addCriterion("college between", value1, value2, "college");
			return (Criteria) this;
		}

		public Criteria andCollegeNotBetween(String value1, String value2) {
			addCriterion("college not between", value1, value2, "college");
			return (Criteria) this;
		}

		public Criteria andMajorIsNull() {
			addCriterion("major is null");
			return (Criteria) this;
		}

		public Criteria andMajorIsNotNull() {
			addCriterion("major is not null");
			return (Criteria) this;
		}

		public Criteria andMajorEqualTo(String value) {
			addCriterion("major =", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotEqualTo(String value) {
			addCriterion("major <>", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThan(String value) {
			addCriterion("major >", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorGreaterThanOrEqualTo(String value) {
			addCriterion("major >=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThan(String value) {
			addCriterion("major <", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLessThanOrEqualTo(String value) {
			addCriterion("major <=", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorLike(String value) {
			addCriterion("major like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotLike(String value) {
			addCriterion("major not like", value, "major");
			return (Criteria) this;
		}

		public Criteria andMajorIn(List<String> values) {
			addCriterion("major in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotIn(List<String> values) {
			addCriterion("major not in", values, "major");
			return (Criteria) this;
		}

		public Criteria andMajorBetween(String value1, String value2) {
			addCriterion("major between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andMajorNotBetween(String value1, String value2) {
			addCriterion("major not between", value1, value2, "major");
			return (Criteria) this;
		}

		public Criteria andVocationIsNull() {
			addCriterion("vocation is null");
			return (Criteria) this;
		}

		public Criteria andVocationIsNotNull() {
			addCriterion("vocation is not null");
			return (Criteria) this;
		}

		public Criteria andVocationEqualTo(String value) {
			addCriterion("vocation =", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationNotEqualTo(String value) {
			addCriterion("vocation <>", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationGreaterThan(String value) {
			addCriterion("vocation >", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationGreaterThanOrEqualTo(String value) {
			addCriterion("vocation >=", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationLessThan(String value) {
			addCriterion("vocation <", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationLessThanOrEqualTo(String value) {
			addCriterion("vocation <=", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationLike(String value) {
			addCriterion("vocation like", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationNotLike(String value) {
			addCriterion("vocation not like", value, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationIn(List<String> values) {
			addCriterion("vocation in", values, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationNotIn(List<String> values) {
			addCriterion("vocation not in", values, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationBetween(String value1, String value2) {
			addCriterion("vocation between", value1, value2, "vocation");
			return (Criteria) this;
		}

		public Criteria andVocationNotBetween(String value1, String value2) {
			addCriterion("vocation not between", value1, value2, "vocation");
			return (Criteria) this;
		}

		public Criteria andWechatIsNull() {
			addCriterion("wechat is null");
			return (Criteria) this;
		}

		public Criteria andWechatIsNotNull() {
			addCriterion("wechat is not null");
			return (Criteria) this;
		}

		public Criteria andWechatEqualTo(String value) {
			addCriterion("wechat =", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotEqualTo(String value) {
			addCriterion("wechat <>", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatGreaterThan(String value) {
			addCriterion("wechat >", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatGreaterThanOrEqualTo(String value) {
			addCriterion("wechat >=", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatLessThan(String value) {
			addCriterion("wechat <", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatLessThanOrEqualTo(String value) {
			addCriterion("wechat <=", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatLike(String value) {
			addCriterion("wechat like", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotLike(String value) {
			addCriterion("wechat not like", value, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatIn(List<String> values) {
			addCriterion("wechat in", values, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotIn(List<String> values) {
			addCriterion("wechat not in", values, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatBetween(String value1, String value2) {
			addCriterion("wechat between", value1, value2, "wechat");
			return (Criteria) this;
		}

		public Criteria andWechatNotBetween(String value1, String value2) {
			addCriterion("wechat not between", value1, value2, "wechat");
			return (Criteria) this;
		}

		public Criteria andQqIsNull() {
			addCriterion("qq is null");
			return (Criteria) this;
		}

		public Criteria andQqIsNotNull() {
			addCriterion("qq is not null");
			return (Criteria) this;
		}

		public Criteria andQqEqualTo(String value) {
			addCriterion("qq =", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotEqualTo(String value) {
			addCriterion("qq <>", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThan(String value) {
			addCriterion("qq >", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThanOrEqualTo(String value) {
			addCriterion("qq >=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThan(String value) {
			addCriterion("qq <", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThanOrEqualTo(String value) {
			addCriterion("qq <=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLike(String value) {
			addCriterion("qq like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotLike(String value) {
			addCriterion("qq not like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqIn(List<String> values) {
			addCriterion("qq in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotIn(List<String> values) {
			addCriterion("qq not in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqBetween(String value1, String value2) {
			addCriterion("qq between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotBetween(String value1, String value2) {
			addCriterion("qq not between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andIscustomIsNull() {
			addCriterion("isCustom is null");
			return (Criteria) this;
		}

		public Criteria andIscustomIsNotNull() {
			addCriterion("isCustom is not null");
			return (Criteria) this;
		}

		public Criteria andIscustomEqualTo(Integer value) {
			addCriterion("isCustom =", value, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomNotEqualTo(Integer value) {
			addCriterion("isCustom <>", value, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomGreaterThan(Integer value) {
			addCriterion("isCustom >", value, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomGreaterThanOrEqualTo(Integer value) {
			addCriterion("isCustom >=", value, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomLessThan(Integer value) {
			addCriterion("isCustom <", value, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomLessThanOrEqualTo(Integer value) {
			addCriterion("isCustom <=", value, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomIn(List<Integer> values) {
			addCriterion("isCustom in", values, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomNotIn(List<Integer> values) {
			addCriterion("isCustom not in", values, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomBetween(Integer value1, Integer value2) {
			addCriterion("isCustom between", value1, value2, "iscustom");
			return (Criteria) this;
		}

		public Criteria andIscustomNotBetween(Integer value1, Integer value2) {
			addCriterion("isCustom not between", value1, value2, "iscustom");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(Integer value) {
			addCriterion("level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(Integer value) {
			addCriterion("level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(Integer value) {
			addCriterion("level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(Integer value) {
			addCriterion("level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(Integer value) {
			addCriterion("level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<Integer> values) {
			addCriterion("level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<Integer> values) {
			addCriterion("level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(Integer value1, Integer value2) {
			addCriterion("level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("level not between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoIsNull() {
			addCriterion("encryptedInfo is null");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoIsNotNull() {
			addCriterion("encryptedInfo is not null");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoEqualTo(String value) {
			addCriterion("encryptedInfo =", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoNotEqualTo(String value) {
			addCriterion("encryptedInfo <>", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoGreaterThan(String value) {
			addCriterion("encryptedInfo >", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoGreaterThanOrEqualTo(String value) {
			addCriterion("encryptedInfo >=", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoLessThan(String value) {
			addCriterion("encryptedInfo <", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoLessThanOrEqualTo(String value) {
			addCriterion("encryptedInfo <=", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoLike(String value) {
			addCriterion("encryptedInfo like", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoNotLike(String value) {
			addCriterion("encryptedInfo not like", value, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoIn(List<String> values) {
			addCriterion("encryptedInfo in", values, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoNotIn(List<String> values) {
			addCriterion("encryptedInfo not in", values, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoBetween(String value1, String value2) {
			addCriterion("encryptedInfo between", value1, value2, "encryptedinfo");
			return (Criteria) this;
		}

		public Criteria andEncryptedinfoNotBetween(String value1, String value2) {
			addCriterion("encryptedInfo not between", value1, value2, "encryptedinfo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table custom
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 25 16:45:53 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}