package com.hg.hgc.web.model;

import java.util.Date;

public class CustomFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_flow.customFlowId
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer customflowid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_flow.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer customid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_flow.guideID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer guideid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom_flow.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_flow.customFlowId
     *
     * @return the value of custom_flow.customFlowId
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getCustomflowid() {
        return customflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_flow.customFlowId
     *
     * @param customflowid the value for custom_flow.customFlowId
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCustomflowid(Integer customflowid) {
        this.customflowid = customflowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_flow.customID
     *
     * @return the value of custom_flow.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getCustomid() {
        return customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_flow.customID
     *
     * @param customid the value for custom_flow.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCustomid(Integer customid) {
        this.customid = customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_flow.guideID
     *
     * @return the value of custom_flow.guideID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getGuideid() {
        return guideid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_flow.guideID
     *
     * @param guideid the value for custom_flow.guideID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setGuideid(Integer guideid) {
        this.guideid = guideid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom_flow.createDate
     *
     * @return the value of custom_flow.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom_flow.createDate
     *
     * @param createdate the value for custom_flow.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}