package com.hg.hgc.web.model;

import java.util.Date;

public class Custom {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.customID
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private Integer customid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.name
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.pwd
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.mobile
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.phone
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.mobile2
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String mobile2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.introduce
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String introduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.gender
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private Byte gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.occupation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String occupation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.IDCardFilePath
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String idcardfilepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.IDCardAuth
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String idcardauth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.logoFilePath
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String logofilepath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.birthday
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.hometown
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String hometown;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.highestEducation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String highesteducation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.college
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String college;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.major
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String major;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.vocation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String vocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.wechat
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String wechat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.qq
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.email
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.isCustom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private Integer iscustom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.level
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custom.encryptedInfo
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	private String encryptedinfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.customID
	 * @return  the value of custom.customID
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public Integer getCustomid() {
		return customid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.customID
	 * @param customid  the value for custom.customID
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setCustomid(Integer customid) {
		this.customid = customid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.name
	 * @return  the value of custom.name
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.name
	 * @param name  the value for custom.name
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.pwd
	 * @return  the value of custom.pwd
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.pwd
	 * @param pwd  the value for custom.pwd
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.mobile
	 * @return  the value of custom.mobile
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.mobile
	 * @param mobile  the value for custom.mobile
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.phone
	 * @return  the value of custom.phone
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.phone
	 * @param phone  the value for custom.phone
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.mobile2
	 * @return  the value of custom.mobile2
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getMobile2() {
		return mobile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.mobile2
	 * @param mobile2  the value for custom.mobile2
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setMobile2(String mobile2) {
		this.mobile2 = mobile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.introduce
	 * @return  the value of custom.introduce
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.introduce
	 * @param introduce  the value for custom.introduce
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.gender
	 * @return  the value of custom.gender
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.gender
	 * @param gender  the value for custom.gender
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.occupation
	 * @return  the value of custom.occupation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getOccupation() {
		return occupation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.occupation
	 * @param occupation  the value for custom.occupation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.IDCardFilePath
	 * @return  the value of custom.IDCardFilePath
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getIdcardfilepath() {
		return idcardfilepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.IDCardFilePath
	 * @param idcardfilepath  the value for custom.IDCardFilePath
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setIdcardfilepath(String idcardfilepath) {
		this.idcardfilepath = idcardfilepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.IDCardAuth
	 * @return  the value of custom.IDCardAuth
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getIdcardauth() {
		return idcardauth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.IDCardAuth
	 * @param idcardauth  the value for custom.IDCardAuth
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setIdcardauth(String idcardauth) {
		this.idcardauth = idcardauth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.logoFilePath
	 * @return  the value of custom.logoFilePath
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getLogofilepath() {
		return logofilepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.logoFilePath
	 * @param logofilepath  the value for custom.logoFilePath
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setLogofilepath(String logofilepath) {
		this.logofilepath = logofilepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.birthday
	 * @return  the value of custom.birthday
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.birthday
	 * @param birthday  the value for custom.birthday
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.hometown
	 * @return  the value of custom.hometown
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getHometown() {
		return hometown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.hometown
	 * @param hometown  the value for custom.hometown
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setHometown(String hometown) {
		this.hometown = hometown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.highestEducation
	 * @return  the value of custom.highestEducation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getHighesteducation() {
		return highesteducation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.highestEducation
	 * @param highesteducation  the value for custom.highestEducation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setHighesteducation(String highesteducation) {
		this.highesteducation = highesteducation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.college
	 * @return  the value of custom.college
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getCollege() {
		return college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.college
	 * @param college  the value for custom.college
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setCollege(String college) {
		this.college = college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.major
	 * @return  the value of custom.major
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getMajor() {
		return major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.major
	 * @param major  the value for custom.major
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setMajor(String major) {
		this.major = major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.vocation
	 * @return  the value of custom.vocation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getVocation() {
		return vocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.vocation
	 * @param vocation  the value for custom.vocation
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setVocation(String vocation) {
		this.vocation = vocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.wechat
	 * @return  the value of custom.wechat
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getWechat() {
		return wechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.wechat
	 * @param wechat  the value for custom.wechat
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.qq
	 * @return  the value of custom.qq
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.qq
	 * @param qq  the value for custom.qq
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.email
	 * @return  the value of custom.email
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.email
	 * @param email  the value for custom.email
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.isCustom
	 * @return  the value of custom.isCustom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public Integer getIscustom() {
		return iscustom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.isCustom
	 * @param iscustom  the value for custom.isCustom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setIscustom(Integer iscustom) {
		this.iscustom = iscustom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.level
	 * @return  the value of custom.level
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.level
	 * @param level  the value for custom.level
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custom.encryptedInfo
	 * @return  the value of custom.encryptedInfo
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public String getEncryptedinfo() {
		return encryptedinfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custom.encryptedInfo
	 * @param encryptedinfo  the value for custom.encryptedInfo
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	public void setEncryptedinfo(String encryptedinfo) {
		this.encryptedinfo = encryptedinfo;
	}
}