package com.hg.hgc.web.model;

public class GuideDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.guideDetailID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer guidedetailid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer customid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.liveTime
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer livetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.haveCar
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Byte havecar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.guideCardAuth
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer guidecardauth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.point
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Float point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.filepath
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String filepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.guideDetailID
     *
     * @return the value of guide_detail.guideDetailID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getGuidedetailid() {
        return guidedetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.guideDetailID
     *
     * @param guidedetailid the value for guide_detail.guideDetailID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setGuidedetailid(Integer guidedetailid) {
        this.guidedetailid = guidedetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.customID
     *
     * @return the value of guide_detail.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getCustomid() {
        return customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.customID
     *
     * @param customid the value for guide_detail.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCustomid(Integer customid) {
        this.customid = customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.liveTime
     *
     * @return the value of guide_detail.liveTime
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getLivetime() {
        return livetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.liveTime
     *
     * @param livetime the value for guide_detail.liveTime
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setLivetime(Integer livetime) {
        this.livetime = livetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.haveCar
     *
     * @return the value of guide_detail.haveCar
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Byte getHavecar() {
        return havecar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.haveCar
     *
     * @param havecar the value for guide_detail.haveCar
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setHavecar(Byte havecar) {
        this.havecar = havecar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.guideCardAuth
     *
     * @return the value of guide_detail.guideCardAuth
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getGuidecardauth() {
        return guidecardauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.guideCardAuth
     *
     * @param guidecardauth the value for guide_detail.guideCardAuth
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setGuidecardauth(Integer guidecardauth) {
        this.guidecardauth = guidecardauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.point
     *
     * @return the value of guide_detail.point
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Float getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.point
     *
     * @param point the value for guide_detail.point
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setPoint(Float point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.filepath
     *
     * @return the value of guide_detail.filepath
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.filepath
     *
     * @param filepath the value for guide_detail.filepath
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
}