package com.hg.hgc.web.model;

import java.util.Date;

public class GuideService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.guideService
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer guideservice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer customid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.project
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.cost
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Long cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.status
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.serviceType
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String servicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_service.expenseExplanation
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String expenseexplanation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.guideService
     *
     * @return the value of guide_service.guideService
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getGuideservice() {
        return guideservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.guideService
     *
     * @param guideservice the value for guide_service.guideService
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setGuideservice(Integer guideservice) {
        this.guideservice = guideservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.customID
     *
     * @return the value of guide_service.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getCustomid() {
        return customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.customID
     *
     * @param customid the value for guide_service.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCustomid(Integer customid) {
        this.customid = customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.project
     *
     * @return the value of guide_service.project
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.project
     *
     * @param project the value for guide_service.project
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setProject(String project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.cost
     *
     * @return the value of guide_service.cost
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Long getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.cost
     *
     * @param cost the value for guide_service.cost
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCost(Long cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.status
     *
     * @return the value of guide_service.status
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.status
     *
     * @param status the value for guide_service.status
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.createDate
     *
     * @return the value of guide_service.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.createDate
     *
     * @param createdate the value for guide_service.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.serviceType
     *
     * @return the value of guide_service.serviceType
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getServicetype() {
        return servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.serviceType
     *
     * @param servicetype the value for guide_service.serviceType
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setServicetype(String servicetype) {
        this.servicetype = servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_service.expenseExplanation
     *
     * @return the value of guide_service.expenseExplanation
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getExpenseexplanation() {
        return expenseexplanation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_service.expenseExplanation
     *
     * @param expenseexplanation the value for guide_service.expenseExplanation
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setExpenseexplanation(String expenseexplanation) {
        this.expenseexplanation = expenseexplanation;
    }
}