package com.hg.hgc.web.model;

import java.util.ArrayList;
import java.util.List;

public class GuideDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public GuideDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGuidedetailidIsNull() {
            addCriterion("guideDetailID is null");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidIsNotNull() {
            addCriterion("guideDetailID is not null");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidEqualTo(Integer value) {
            addCriterion("guideDetailID =", value, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidNotEqualTo(Integer value) {
            addCriterion("guideDetailID <>", value, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidGreaterThan(Integer value) {
            addCriterion("guideDetailID >", value, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidGreaterThanOrEqualTo(Integer value) {
            addCriterion("guideDetailID >=", value, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidLessThan(Integer value) {
            addCriterion("guideDetailID <", value, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidLessThanOrEqualTo(Integer value) {
            addCriterion("guideDetailID <=", value, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidIn(List<Integer> values) {
            addCriterion("guideDetailID in", values, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidNotIn(List<Integer> values) {
            addCriterion("guideDetailID not in", values, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidBetween(Integer value1, Integer value2) {
            addCriterion("guideDetailID between", value1, value2, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andGuidedetailidNotBetween(Integer value1, Integer value2) {
            addCriterion("guideDetailID not between", value1, value2, "guidedetailid");
            return (Criteria) this;
        }

        public Criteria andCustomidIsNull() {
            addCriterion("customID is null");
            return (Criteria) this;
        }

        public Criteria andCustomidIsNotNull() {
            addCriterion("customID is not null");
            return (Criteria) this;
        }

        public Criteria andCustomidEqualTo(Integer value) {
            addCriterion("customID =", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidNotEqualTo(Integer value) {
            addCriterion("customID <>", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidGreaterThan(Integer value) {
            addCriterion("customID >", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidGreaterThanOrEqualTo(Integer value) {
            addCriterion("customID >=", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidLessThan(Integer value) {
            addCriterion("customID <", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidLessThanOrEqualTo(Integer value) {
            addCriterion("customID <=", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidIn(List<Integer> values) {
            addCriterion("customID in", values, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidNotIn(List<Integer> values) {
            addCriterion("customID not in", values, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidBetween(Integer value1, Integer value2) {
            addCriterion("customID between", value1, value2, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidNotBetween(Integer value1, Integer value2) {
            addCriterion("customID not between", value1, value2, "customid");
            return (Criteria) this;
        }

        public Criteria andLivetimeIsNull() {
            addCriterion("liveTime is null");
            return (Criteria) this;
        }

        public Criteria andLivetimeIsNotNull() {
            addCriterion("liveTime is not null");
            return (Criteria) this;
        }

        public Criteria andLivetimeEqualTo(Integer value) {
            addCriterion("liveTime =", value, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeNotEqualTo(Integer value) {
            addCriterion("liveTime <>", value, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeGreaterThan(Integer value) {
            addCriterion("liveTime >", value, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("liveTime >=", value, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeLessThan(Integer value) {
            addCriterion("liveTime <", value, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeLessThanOrEqualTo(Integer value) {
            addCriterion("liveTime <=", value, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeIn(List<Integer> values) {
            addCriterion("liveTime in", values, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeNotIn(List<Integer> values) {
            addCriterion("liveTime not in", values, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeBetween(Integer value1, Integer value2) {
            addCriterion("liveTime between", value1, value2, "livetime");
            return (Criteria) this;
        }

        public Criteria andLivetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("liveTime not between", value1, value2, "livetime");
            return (Criteria) this;
        }

        public Criteria andHavecarIsNull() {
            addCriterion("haveCar is null");
            return (Criteria) this;
        }

        public Criteria andHavecarIsNotNull() {
            addCriterion("haveCar is not null");
            return (Criteria) this;
        }

        public Criteria andHavecarEqualTo(Byte value) {
            addCriterion("haveCar =", value, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarNotEqualTo(Byte value) {
            addCriterion("haveCar <>", value, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarGreaterThan(Byte value) {
            addCriterion("haveCar >", value, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarGreaterThanOrEqualTo(Byte value) {
            addCriterion("haveCar >=", value, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarLessThan(Byte value) {
            addCriterion("haveCar <", value, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarLessThanOrEqualTo(Byte value) {
            addCriterion("haveCar <=", value, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarIn(List<Byte> values) {
            addCriterion("haveCar in", values, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarNotIn(List<Byte> values) {
            addCriterion("haveCar not in", values, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarBetween(Byte value1, Byte value2) {
            addCriterion("haveCar between", value1, value2, "havecar");
            return (Criteria) this;
        }

        public Criteria andHavecarNotBetween(Byte value1, Byte value2) {
            addCriterion("haveCar not between", value1, value2, "havecar");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthIsNull() {
            addCriterion("guideCardAuth is null");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthIsNotNull() {
            addCriterion("guideCardAuth is not null");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthEqualTo(Integer value) {
            addCriterion("guideCardAuth =", value, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthNotEqualTo(Integer value) {
            addCriterion("guideCardAuth <>", value, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthGreaterThan(Integer value) {
            addCriterion("guideCardAuth >", value, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthGreaterThanOrEqualTo(Integer value) {
            addCriterion("guideCardAuth >=", value, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthLessThan(Integer value) {
            addCriterion("guideCardAuth <", value, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthLessThanOrEqualTo(Integer value) {
            addCriterion("guideCardAuth <=", value, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthIn(List<Integer> values) {
            addCriterion("guideCardAuth in", values, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthNotIn(List<Integer> values) {
            addCriterion("guideCardAuth not in", values, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthBetween(Integer value1, Integer value2) {
            addCriterion("guideCardAuth between", value1, value2, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andGuidecardauthNotBetween(Integer value1, Integer value2) {
            addCriterion("guideCardAuth not between", value1, value2, "guidecardauth");
            return (Criteria) this;
        }

        public Criteria andPointIsNull() {
            addCriterion("point is null");
            return (Criteria) this;
        }

        public Criteria andPointIsNotNull() {
            addCriterion("point is not null");
            return (Criteria) this;
        }

        public Criteria andPointEqualTo(Float value) {
            addCriterion("point =", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotEqualTo(Float value) {
            addCriterion("point <>", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointGreaterThan(Float value) {
            addCriterion("point >", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointGreaterThanOrEqualTo(Float value) {
            addCriterion("point >=", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointLessThan(Float value) {
            addCriterion("point <", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointLessThanOrEqualTo(Float value) {
            addCriterion("point <=", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointIn(List<Float> values) {
            addCriterion("point in", values, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotIn(List<Float> values) {
            addCriterion("point not in", values, "point");
            return (Criteria) this;
        }

        public Criteria andPointBetween(Float value1, Float value2) {
            addCriterion("point between", value1, value2, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotBetween(Float value1, Float value2) {
            addCriterion("point not between", value1, value2, "point");
            return (Criteria) this;
        }

        public Criteria andFilepathIsNull() {
            addCriterion("filepath is null");
            return (Criteria) this;
        }

        public Criteria andFilepathIsNotNull() {
            addCriterion("filepath is not null");
            return (Criteria) this;
        }

        public Criteria andFilepathEqualTo(String value) {
            addCriterion("filepath =", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotEqualTo(String value) {
            addCriterion("filepath <>", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathGreaterThan(String value) {
            addCriterion("filepath >", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathGreaterThanOrEqualTo(String value) {
            addCriterion("filepath >=", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathLessThan(String value) {
            addCriterion("filepath <", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathLessThanOrEqualTo(String value) {
            addCriterion("filepath <=", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathLike(String value) {
            addCriterion("filepath like", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotLike(String value) {
            addCriterion("filepath not like", value, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathIn(List<String> values) {
            addCriterion("filepath in", values, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotIn(List<String> values) {
            addCriterion("filepath not in", values, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathBetween(String value1, String value2) {
            addCriterion("filepath between", value1, value2, "filepath");
            return (Criteria) this;
        }

        public Criteria andFilepathNotBetween(String value1, String value2) {
            addCriterion("filepath not between", value1, value2, "filepath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_detail
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 02 22:48:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}