package com.hg.hgc.web.model;

public class GuideDetailWithBLOBs extends GuideDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.cityIntroduction
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String cityintroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guide_detail.labelInfo
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String labelinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.cityIntroduction
     *
     * @return the value of guide_detail.cityIntroduction
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getCityintroduction() {
        return cityintroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.cityIntroduction
     *
     * @param cityintroduction the value for guide_detail.cityIntroduction
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCityintroduction(String cityintroduction) {
        this.cityintroduction = cityintroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guide_detail.labelInfo
     *
     * @return the value of guide_detail.labelInfo
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getLabelinfo() {
        return labelinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guide_detail.labelInfo
     *
     * @param labelinfo the value for guide_detail.labelInfo
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setLabelinfo(String labelinfo) {
        this.labelinfo = labelinfo;
    }
}