package com.hg.hgc.web.model;

import java.util.Date;

public class HomeActivitie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.homeActivitieID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer homeactivitieid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.title
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.introduction
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.author
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.startDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.endDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.indexImageFile
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String indeximagefile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_activitie.content
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.homeActivitieID
     *
     * @return the value of home_activitie.homeActivitieID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getHomeactivitieid() {
        return homeactivitieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.homeActivitieID
     *
     * @param homeactivitieid the value for home_activitie.homeActivitieID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setHomeactivitieid(Integer homeactivitieid) {
        this.homeactivitieid = homeactivitieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.title
     *
     * @return the value of home_activitie.title
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.title
     *
     * @param title the value for home_activitie.title
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.introduction
     *
     * @return the value of home_activitie.introduction
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.introduction
     *
     * @param introduction the value for home_activitie.introduction
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.author
     *
     * @return the value of home_activitie.author
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.author
     *
     * @param author the value for home_activitie.author
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.createDate
     *
     * @return the value of home_activitie.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.createDate
     *
     * @param createdate the value for home_activitie.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.startDate
     *
     * @return the value of home_activitie.startDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.startDate
     *
     * @param startdate the value for home_activitie.startDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.endDate
     *
     * @return the value of home_activitie.endDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.endDate
     *
     * @param enddate the value for home_activitie.endDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.indexImageFile
     *
     * @return the value of home_activitie.indexImageFile
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getIndeximagefile() {
        return indeximagefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.indexImageFile
     *
     * @param indeximagefile the value for home_activitie.indexImageFile
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setIndeximagefile(String indeximagefile) {
        this.indeximagefile = indeximagefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_activitie.content
     *
     * @return the value of home_activitie.content
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_activitie.content
     *
     * @param content the value for home_activitie.content
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}