package com.hg.hgc.web.model;

import java.util.Date;

public class ProjectImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_image.projectImageID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer projectimageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_image.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Integer customid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_image.imageTips
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String imagetips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_image.imagePath
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String imagepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_image.imageType
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private String imagetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_image.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_image.projectImageID
     *
     * @return the value of project_image.projectImageID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getProjectimageid() {
        return projectimageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_image.projectImageID
     *
     * @param projectimageid the value for project_image.projectImageID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setProjectimageid(Integer projectimageid) {
        this.projectimageid = projectimageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_image.customID
     *
     * @return the value of project_image.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Integer getCustomid() {
        return customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_image.customID
     *
     * @param customid the value for project_image.customID
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCustomid(Integer customid) {
        this.customid = customid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_image.imageTips
     *
     * @return the value of project_image.imageTips
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getImagetips() {
        return imagetips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_image.imageTips
     *
     * @param imagetips the value for project_image.imageTips
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setImagetips(String imagetips) {
        this.imagetips = imagetips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_image.imagePath
     *
     * @return the value of project_image.imagePath
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_image.imagePath
     *
     * @param imagepath the value for project_image.imagePath
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_image.imageType
     *
     * @return the value of project_image.imageType
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getImagetype() {
        return imagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_image.imageType
     *
     * @param imagetype the value for project_image.imageType
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setImagetype(String imagetype) {
        this.imagetype = imagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_image.createDate
     *
     * @return the value of project_image.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_image.createDate
     *
     * @param createdate the value for project_image.createDate
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}