package com.hg.hgc.web.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public ProjectImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectimageidIsNull() {
            addCriterion("projectImageID is null");
            return (Criteria) this;
        }

        public Criteria andProjectimageidIsNotNull() {
            addCriterion("projectImageID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectimageidEqualTo(Integer value) {
            addCriterion("projectImageID =", value, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidNotEqualTo(Integer value) {
            addCriterion("projectImageID <>", value, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidGreaterThan(Integer value) {
            addCriterion("projectImageID >", value, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidGreaterThanOrEqualTo(Integer value) {
            addCriterion("projectImageID >=", value, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidLessThan(Integer value) {
            addCriterion("projectImageID <", value, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidLessThanOrEqualTo(Integer value) {
            addCriterion("projectImageID <=", value, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidIn(List<Integer> values) {
            addCriterion("projectImageID in", values, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidNotIn(List<Integer> values) {
            addCriterion("projectImageID not in", values, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidBetween(Integer value1, Integer value2) {
            addCriterion("projectImageID between", value1, value2, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andProjectimageidNotBetween(Integer value1, Integer value2) {
            addCriterion("projectImageID not between", value1, value2, "projectimageid");
            return (Criteria) this;
        }

        public Criteria andCustomidIsNull() {
            addCriterion("customID is null");
            return (Criteria) this;
        }

        public Criteria andCustomidIsNotNull() {
            addCriterion("customID is not null");
            return (Criteria) this;
        }

        public Criteria andCustomidEqualTo(Integer value) {
            addCriterion("customID =", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidNotEqualTo(Integer value) {
            addCriterion("customID <>", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidGreaterThan(Integer value) {
            addCriterion("customID >", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidGreaterThanOrEqualTo(Integer value) {
            addCriterion("customID >=", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidLessThan(Integer value) {
            addCriterion("customID <", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidLessThanOrEqualTo(Integer value) {
            addCriterion("customID <=", value, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidIn(List<Integer> values) {
            addCriterion("customID in", values, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidNotIn(List<Integer> values) {
            addCriterion("customID not in", values, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidBetween(Integer value1, Integer value2) {
            addCriterion("customID between", value1, value2, "customid");
            return (Criteria) this;
        }

        public Criteria andCustomidNotBetween(Integer value1, Integer value2) {
            addCriterion("customID not between", value1, value2, "customid");
            return (Criteria) this;
        }

        public Criteria andImagetipsIsNull() {
            addCriterion("imageTips is null");
            return (Criteria) this;
        }

        public Criteria andImagetipsIsNotNull() {
            addCriterion("imageTips is not null");
            return (Criteria) this;
        }

        public Criteria andImagetipsEqualTo(String value) {
            addCriterion("imageTips =", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsNotEqualTo(String value) {
            addCriterion("imageTips <>", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsGreaterThan(String value) {
            addCriterion("imageTips >", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsGreaterThanOrEqualTo(String value) {
            addCriterion("imageTips >=", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsLessThan(String value) {
            addCriterion("imageTips <", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsLessThanOrEqualTo(String value) {
            addCriterion("imageTips <=", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsLike(String value) {
            addCriterion("imageTips like", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsNotLike(String value) {
            addCriterion("imageTips not like", value, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsIn(List<String> values) {
            addCriterion("imageTips in", values, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsNotIn(List<String> values) {
            addCriterion("imageTips not in", values, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsBetween(String value1, String value2) {
            addCriterion("imageTips between", value1, value2, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagetipsNotBetween(String value1, String value2) {
            addCriterion("imageTips not between", value1, value2, "imagetips");
            return (Criteria) this;
        }

        public Criteria andImagepathIsNull() {
            addCriterion("imagePath is null");
            return (Criteria) this;
        }

        public Criteria andImagepathIsNotNull() {
            addCriterion("imagePath is not null");
            return (Criteria) this;
        }

        public Criteria andImagepathEqualTo(String value) {
            addCriterion("imagePath =", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathNotEqualTo(String value) {
            addCriterion("imagePath <>", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathGreaterThan(String value) {
            addCriterion("imagePath >", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathGreaterThanOrEqualTo(String value) {
            addCriterion("imagePath >=", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathLessThan(String value) {
            addCriterion("imagePath <", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathLessThanOrEqualTo(String value) {
            addCriterion("imagePath <=", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathLike(String value) {
            addCriterion("imagePath like", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathNotLike(String value) {
            addCriterion("imagePath not like", value, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathIn(List<String> values) {
            addCriterion("imagePath in", values, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathNotIn(List<String> values) {
            addCriterion("imagePath not in", values, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathBetween(String value1, String value2) {
            addCriterion("imagePath between", value1, value2, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagepathNotBetween(String value1, String value2) {
            addCriterion("imagePath not between", value1, value2, "imagepath");
            return (Criteria) this;
        }

        public Criteria andImagetypeIsNull() {
            addCriterion("imageType is null");
            return (Criteria) this;
        }

        public Criteria andImagetypeIsNotNull() {
            addCriterion("imageType is not null");
            return (Criteria) this;
        }

        public Criteria andImagetypeEqualTo(String value) {
            addCriterion("imageType =", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeNotEqualTo(String value) {
            addCriterion("imageType <>", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeGreaterThan(String value) {
            addCriterion("imageType >", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeGreaterThanOrEqualTo(String value) {
            addCriterion("imageType >=", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeLessThan(String value) {
            addCriterion("imageType <", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeLessThanOrEqualTo(String value) {
            addCriterion("imageType <=", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeLike(String value) {
            addCriterion("imageType like", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeNotLike(String value) {
            addCriterion("imageType not like", value, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeIn(List<String> values) {
            addCriterion("imageType in", values, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeNotIn(List<String> values) {
            addCriterion("imageType not in", values, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeBetween(String value1, String value2) {
            addCriterion("imageType between", value1, value2, "imagetype");
            return (Criteria) this;
        }

        public Criteria andImagetypeNotBetween(String value1, String value2) {
            addCriterion("imageType not between", value1, value2, "imagetype");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_image
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 02 22:48:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}