package com.hg.hgc.web.dao;

import com.hg.hgc.core.generic.GenericDao;
import com.hg.hgc.web.model.Custom;
import com.hg.hgc.web.model.CustomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomMapper extends GenericDao<Custom, Integer>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	long countByExample(CustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int deleteByExample(CustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer customid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int insert(Custom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int insertSelective(Custom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	List<Custom> selectByExample(CustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	Custom selectByPrimaryKey(Integer customid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Custom record, @Param("example") CustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int updateByExample(@Param("record") Custom record, @Param("example") CustomExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int updateByPrimaryKeySelective(Custom record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table custom
	 * @mbg.generated  Sun Jul 02 22:50:07 CST 2017
	 */
	int updateByPrimaryKey(Custom record);
    
    
}