package com.hg.hgc.web.dao;

import com.hg.hgc.core.generic.GenericDao;
import com.hg.hgc.web.model.CustomFlow;
import com.hg.hgc.web.model.CustomFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomFlowMapper extends GenericDao<CustomFlow, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    long countByExample(CustomFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByExample(CustomFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByPrimaryKey(Integer customflowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insert(CustomFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insertSelective(CustomFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    List<CustomFlow> selectByExample(CustomFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    CustomFlow selectByPrimaryKey(Integer customflowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") CustomFlow record, @Param("example") CustomFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExample(@Param("record") CustomFlow record, @Param("example") CustomFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKeySelective(CustomFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_flow
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKey(CustomFlow record);
}