package com.hg.hgc.web.dao;

import com.hg.hgc.core.generic.GenericDao;
import com.hg.hgc.web.model.GuideDetail;
import com.hg.hgc.web.model.GuideDetailExample;
import com.hg.hgc.web.model.GuideDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuideDetailMapper extends GenericDao<GuideDetail, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    long countByExample(GuideDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByExample(GuideDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByPrimaryKey(Integer guidedetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insert(GuideDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insertSelective(GuideDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    List<GuideDetailWithBLOBs> selectByExampleWithBLOBs(GuideDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    List<GuideDetail> selectByExample(GuideDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    GuideDetailWithBLOBs selectByPrimaryKey(Integer guidedetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") GuideDetailWithBLOBs record, @Param("example") GuideDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") GuideDetailWithBLOBs record, @Param("example") GuideDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExample(@Param("record") GuideDetail record, @Param("example") GuideDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKeySelective(GuideDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(GuideDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guide_detail
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKey(GuideDetail record);
}