package com.hg.hgc.web.dao;

import com.hg.hgc.core.generic.GenericDao;
import com.hg.hgc.web.model.HomeActivitie;
import com.hg.hgc.web.model.HomeActivitieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeActivitieMapper extends GenericDao<HomeActivitie, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    long countByExample(HomeActivitieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByExample(HomeActivitieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByPrimaryKey(Integer homeactivitieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insert(HomeActivitie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insertSelective(HomeActivitie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    List<HomeActivitie> selectByExampleWithBLOBs(HomeActivitieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    List<HomeActivitie> selectByExample(HomeActivitieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    HomeActivitie selectByPrimaryKey(Integer homeactivitieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") HomeActivitie record, @Param("example") HomeActivitieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") HomeActivitie record, @Param("example") HomeActivitieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExample(@Param("record") HomeActivitie record, @Param("example") HomeActivitieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKeySelective(HomeActivitie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(HomeActivitie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_activitie
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKey(HomeActivitie record);
}