package com.hg.hgc.web.dao;

import com.hg.hgc.core.generic.GenericDao;
import com.hg.hgc.web.model.ProjectImage;
import com.hg.hgc.web.model.ProjectImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectImageMapper extends GenericDao<ProjectImage, Integer>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    long countByExample(ProjectImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByExample(ProjectImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int deleteByPrimaryKey(Integer projectimageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insert(ProjectImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int insertSelective(ProjectImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    List<ProjectImage> selectByExample(ProjectImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    ProjectImage selectByPrimaryKey(Integer projectimageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") ProjectImage record, @Param("example") ProjectImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByExample(@Param("record") ProjectImage record, @Param("example") ProjectImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKeySelective(ProjectImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_image
     *
     * @mbg.generated Sun Jul 02 22:48:21 CST 2017
     */
    int updateByPrimaryKey(ProjectImage record);
}